inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^\s*#'

Style/FileName:
  Exclude:
    - 'lib/bemer-bootstrap.rb'
